### ISSUE TITLE
Strange behavior when doing R CMD check

### ISSUE THREAD

**Issue by CaboML** [jfiksel/mockery#27]
After creating the stub and designing my tests with testthat, I run devtools::test() with everything OK. 

But when I run devtools::check () all tests fail. 

Do you have any idea?

**Comment by ivd** [comment]
@CaboML Thanks for opening an issue. I can't reproduce this; can you paste your output from `devtools::check()`?

**Comment by CaboML** [comment]
I realize that the problem, I was facing, does not have anything to do with mockery. Sorry
